# Generated by Django 5.2.1 on 2025-05-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BairstowRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecuacion', models.CharField(max_length=255)),
                ('r_inicial', models.FloatField()),
                ('s_inicial', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('max_iter', models.IntegerField()),
                ('raices', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('grafica', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
